site :opscode
cookbook '7-zip', '~> 1.0.2'
cookbook 'build-essential', '~> 2.0.6'
cookbook 'pacman'
cookbook 'ark', '~> 0.9.0'
cookbook 'chef_handler', '~> 1.1.6'
cookbook 'java', '~> 1.27.0'
cookbook 'logrotate', '~> 1.6.0'
cookbook 'windows', '~> 1.34.2'
cookbook 'yum-mysql-community', '~> 0.1.10'